### ISSUE TITLE
Problema de alineacion de imagenes en la etiqueta 'tarifa'

### ISSUE THREAD

**Issue by iamcarlosmunoz** [iamcarlosmunoz/web-basicSiteWeb#1]
Se presento el problema de alineacion en el apartado tarifas, ya que las imagenes utlizadas son de distinto tamaño, que al trararlas en el style.css para añadirle un circulo blanco a cada imagen se hace mas evidente el problema.

**Comment by CarlosJMR** [comment]
Fue solucionado modificado el tamaño de las imagenes a 512x512 para las 3 que se muestran en la categoria TARIFAS
